name: Trivy Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t safenotes-app .

      - name: Scan Docker image with Trivy
        #uses: aquasecurity/trivy-action@v0.63.0
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          image-ref: safenotes-app:latest
