name: Seguridad en CI

on:
  push:
    branches:
      - main

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      #- name: Ejecutar pruebas
      #  run: npm test

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "SafeNotes"
          scanPath: "."
          format: "HTML"
